package in.ohmama.omchat.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import in.ohmama.omchat.model.OmUser;
import in.ohmama.omchat.model.OmMessage;
import in.ohmama.omchat.model.OmComingMsg;

import in.ohmama.omchat.model.OmUserDao;
import in.ohmama.omchat.model.OmMessageDao;
import in.ohmama.omchat.model.OmComingMsgDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig omUserDaoConfig;
    private final DaoConfig omMessageDaoConfig;
    private final DaoConfig omComingMsgDaoConfig;

    private final OmUserDao omUserDao;
    private final OmMessageDao omMessageDao;
    private final OmComingMsgDao omComingMsgDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        omUserDaoConfig = daoConfigMap.get(OmUserDao.class).clone();
        omUserDaoConfig.initIdentityScope(type);

        omMessageDaoConfig = daoConfigMap.get(OmMessageDao.class).clone();
        omMessageDaoConfig.initIdentityScope(type);

        omComingMsgDaoConfig = daoConfigMap.get(OmComingMsgDao.class).clone();
        omComingMsgDaoConfig.initIdentityScope(type);

        omUserDao = new OmUserDao(omUserDaoConfig, this);
        omMessageDao = new OmMessageDao(omMessageDaoConfig, this);
        omComingMsgDao = new OmComingMsgDao(omComingMsgDaoConfig, this);

        registerDao(OmUser.class, omUserDao);
        registerDao(OmMessage.class, omMessageDao);
        registerDao(OmComingMsg.class, omComingMsgDao);
    }
    
    public void clear() {
        omUserDaoConfig.getIdentityScope().clear();
        omMessageDaoConfig.getIdentityScope().clear();
        omComingMsgDaoConfig.getIdentityScope().clear();
    }

    public OmUserDao getOmUserDao() {
        return omUserDao;
    }

    public OmMessageDao getOmMessageDao() {
        return omMessageDao;
    }

    public OmComingMsgDao getOmComingMsgDao() {
        return omComingMsgDao;
    }

}
