package in.ohmama.omchat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OM_COMING_MSG".
 */
public class OmComingMsg {

    private Long id;
    private String userName;
    private Integer typeId;
    private Integer count;

    public OmComingMsg() {
    }

    public OmComingMsg(Long id) {
        this.id = id;
    }

    public OmComingMsg(Long id, String userName, Integer typeId, Integer count) {
        this.id = id;
        this.userName = userName;
        this.typeId = typeId;
        this.count = count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

}
