package in.ohmama.omchat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OM_MESSAGE".
 */
public class OmMessage {

    private Long id;
    private Integer typeId;
    private String textMsg;
    private String userName;
    private java.util.Date time;
    private Integer inOut;
    private Integer mediaDuration;
    private Boolean isRead;

    public OmMessage() {
    }

    public OmMessage(Long id) {
        this.id = id;
    }

    public OmMessage(Long id, Integer typeId, String textMsg, String userName, java.util.Date time, Integer inOut, Integer mediaDuration, Boolean isRead) {
        this.id = id;
        this.typeId = typeId;
        this.textMsg = textMsg;
        this.userName = userName;
        this.time = time;
        this.inOut = inOut;
        this.mediaDuration = mediaDuration;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public String getTextMsg() {
        return textMsg;
    }

    public void setTextMsg(String textMsg) {
        this.textMsg = textMsg;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public java.util.Date getTime() {
        return time;
    }

    public void setTime(java.util.Date time) {
        this.time = time;
    }

    public Integer getInOut() {
        return inOut;
    }

    public void setInOut(Integer inOut) {
        this.inOut = inOut;
    }

    public Integer getMediaDuration() {
        return mediaDuration;
    }

    public void setMediaDuration(Integer mediaDuration) {
        this.mediaDuration = mediaDuration;
    }

    public Boolean getIsRead() {
        return isRead;
    }

    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

}
