package in.ohmama.omchat.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "OM_USER".
 */
public class OmUser {

    private String nickName;
    private Long id;
    private String userName;
    private String status;
    private String avatorPath;
    private String from;
    private String mood;
    private Integer size;
    private Integer typeId;

    public OmUser() {
    }

    public OmUser(Long id) {
        this.id = id;
    }

    public OmUser(String nickName, Long id, String userName, String status, String avatorPath, String from, String mood, Integer size, Integer typeId) {
        this.nickName = nickName;
        this.id = id;
        this.userName = userName;
        this.status = status;
        this.avatorPath = avatorPath;
        this.from = from;
        this.mood = mood;
        this.size = size;
        this.typeId = typeId;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAvatorPath() {
        return avatorPath;
    }

    public void setAvatorPath(String avatorPath) {
        this.avatorPath = avatorPath;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public Integer getTypeId() {
        return typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

}
